### PR TITLE
Main menu

### PR DESCRIPTION
**Pull request by nyan-ko**
Add window for the main menu and refactor window navigation code

### CODE REVIEW

**Comment by nyan-ko** [comment]
docs to be added

**Review by SMateen21 — APPROVED** [review]
Don't see much to change, looks good!

**Review by meiiph — COMMENTED** [review]
All looks good, just need to double check the WindowName discrepancy mentioned in a comment I added.

**Review by lilyxmeng — DISMISSED** [review]

**Review by SMateen21 — APPROVED** [review]
Looks good! Some documentation to add later on though.

**Review by meiiph — DISMISSED** [review]
Same comment as Solemann, and just make sure not to miss the identifier difference later.

**Review by SMateen21 — APPROVED** [review]
I approve.

**Review by lilyxmeng — APPROVED** [review]

**Pull request merged**
