### PR TITLE
Enum refactor

### PR DESCRIPTION
**Pull request by nyan-ko**
Refactor most classes and tests using Strings for card suits and rank. Note that certain tests that use bogus card values, e.g. new Card("Test", "17") have currently not been updated since I did not know an appropriate replacement for all of them.

### CODE REVIEW

**Comment by nyan-ko** [comment]
full list of invalid tests:
```
ComputerPlayerTest.testSelectCardInvalid()
HandTest.setUp()
HandTest.testRemoveCard()
StandardDeckTest.setUp()
GameStateTest.testUpdateGameObserver()
PlayerGameInteractorTest.testCreateResponsePlayInvalidCard()
PlayerGameInteractorTest.testCreateResponseSkipTurnValid()
PlayerGameInteractorTest.testCreateResponsePickUpCardValid()
```

**Review by lilyxmeng — APPROVED** [review]
Missing javadocs

**Review by SMateen21 — APPROVED** [review]
I do think the use of enums is better than using Strings, the code also becomes more readable and easier to understand. My only gripe with enums is they don't necessarily follow OCP so if someone wanted to add their own card type they'd have to modify the enum. However though, rules have exceptions, and adding a new Suit and Rank does not sound necessary given there is already a full deck of cards. Overall the code looks more readable and polished, so well done. Given the deadline, I'll approve even without the passing tests as I can't see anything that breaks the program immediately, however it'd be best to put out an issue for that, as well as adding documentation to the new classes and tests.

**Review by meiiph — APPROVED** [review]
I think Lily and Solemann mentioned all that needs to be said. :)

**Pull request merged**
