### PR TITLE
UI updates

### PR DESCRIPTION
**Pull request by nyan-ko**
make user interface more interactive, cards now respond to selection and game notifies user of choice validity (e.g. whether a card is valid, whether they can skip), + overall improvement of aesthetics

### CODE REVIEW

**Review by SMateen21 — APPROVED** [review]
Looks great! As long as it works I approve.

**Review by lilyxmeng — APPROVED** [review]
No significant issues, approved.

**Review by meiiph — APPROVED** [review]
👍

**Comment by meiiph** [comment]
Did not change any code itself, merging with previous approvals.

**Pull request merged**
